% Alexander Moreno
% 12-11-2019
%
% [main code at the moment]
% making changes

function [] = Ant_Wire_GUI()
    global Units;
    global AntDim; 
    global Bdim;
    global A;
    global B;
    
    v0 = 'm';
    Units = struct('h',v0,'W',v0,'L',v0,'wT',v0,'phi',v0,'dimx',...
        v0,'dimy',v0,'dimz',v0,'dimI',v0,'dimBF',v0);
    v0 = 0;
    AntDim = struct('h',v0,'ra',v0,'ri',v0,'wT',v0,'N',v0,'O',v0,...
        'phi',v0,'W',v0,'L',v0,'Nxy',v0);
    Bdim  = struct('Nx',v0,'xmin',v0,'xmax',v0,'Ny',v0,'ymin',v0,...
    'ymax',v0,'Nz',v0,'zmin',v0,'zmax',v0,'I',v0,'v','v0'); 
    A = struct('X',v0,'Y',v0,'Z',v0);
    B = struct('BX',v0,'BY',v0,'BZ',v0,'X',v0,'Y',v0,'Z',v0);
    
    SCR = get(0,'Screensize');
    % creates figure
    fx = SCR(3)/4-200; fy = SCR(4)/4-200; fdx = 825; fdy = 400;
    S.fh = figure('numbertitle','off',...
                  'menubar','none',...
                  'units','pixels',...
                  'position',[fx ,fy , fdx, fdy],...
                  'name','Wire Antenna Design Tool',...
                  'resize','off');
    % creates empty plot
    px=50; py=100; pdx=300; pdy=230;
    S.ax = axes('units','pixels','position',[50 100 300 230]);  
    rotate3d on;
    % Toggles will act as the tabs.              
    tg_x  = 5; tg_y  = 355; tg_px = 90; tg_py = 40;
    S.tg(1) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[tg_x, tg_y, tg_px, tg_py],...
                        'string','Rectangular',...
                        'val',1);
    S.tg(2) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[tg_x+tg_px, tg_y, tg_px, tg_py],...
                        'string','Elliptical',...
                        'value',1,...
                        'enable','on');
    S.tg(3) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[tg_x+2*tg_px tg_y tg_px tg_py],...
                        'string','Import',...
                        'value',1,...
                        'enable','on');
    S.tg(4) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[tg_x+6*tg_px tg_y tg_px tg_py],...
                        'string','Run',...
                        'value',1,...
                        'enable','on');
    S.tg(5) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[tg_x+7*tg_px tg_y tg_px tg_py],...
                        'string','Export',...
                        'value',1,...
                        'enable','on');
    S.tg(6) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[tg_x+8*tg_px tg_y tg_px tg_py],...
                        'string','About',...
                        'value',1,...
                        'enable','on');
%% drop down list    
    ddList = {'[m]','[cm]','[mm]','[in]'};
    hList  = {'[mil]','[m]','[cm]','[mm]','[in]'};
    wtList = {'[AWG]','[m]','[cm]','[mm]','[in]'};
    dList  = {'[deg]','[rad]'}; 
    aList  = {'[A]','[mA]','[uA]','[nA]'};
    sList  = {'[FAST]','[SLOW]'};
    
    dd_dx = 50; dd_dy = 25; 
    tx=px+pdx;
    ddx = tx+dd_dx*2;
    % h
    S.dd(1) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[ddx, pdy+py-dd_dy*1.05, dd_dx, dd_dy],...
                 'string',hList);
    % ra
    S.dd(2) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[ddx,pdy+py-dd_dy*2.05, dd_dx, dd_dy],...
                 'string',ddList);  
    % ri
    S.dd(3) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[ddx, pdy+py-dd_dy*3.05, dd_dx, dd_dy],...
                 'string',ddList);  
    % wT
    S.dd(4) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[ddx, pdy+py-dd_dy*4.05, dd_dx+5, dd_dy],...
                 'string',wtList);
    % phi
    S.dd(5) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[ddx, pdy+py-dd_dy*8.05, dd_dx, dd_dy],...
                 'string',dList);    
   % xdim
    S.dim_dd(1) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[tx*1.5+dd_dx*2.4,pdy+py-dd_dy*1.5,dd_dx,...
                 dd_dy],'string',ddList);     
   % ydim
    S.dim_dd(2) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[tx*1.5+dd_dx*2.4,pdy+py-dd_dy*3.25,dd_dx,...
                 dd_dy],'string',ddList);
   % zim
    S.dim_dd(3) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[tx*1.5+dd_dx*2.4,pdy+py-dd_dy*5,dd_dx,...
                 dd_dy],'string',ddList);
    % I 
    S.dim_dd(4) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[ddx, pdy+py-dd_dy*9.05, dd_dx, dd_dy],...
                 'string',aList);
    % SLOW/FAST
    S.dim_dd(5) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[tg_x+6*tg_px-60, tg_y-20, 60, 50],...
                 'string',sList);                    
%% text 
    % h
    S.ep_txt(1) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*1.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'h'});          
    % ra
    S.ep_txt(2) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*2.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'ra'});
    % ri
    S.ep_txt(3) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*3.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'ri'});          
    % wT
    S.ep_txt(4) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*4.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'wT'});
    % N
    S.ep_txt(5) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*5.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'N'});
    % O
    S.ep_txt(6) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*6.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'O'});          
    % phi
    S.ep_txt(7) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*8.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'phi'});
    % W
    S.ep_txt(8) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*2.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'W'});
    % L
    S.ep_txt(9) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*3.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'L'}); 
    % Nxy
    S.ep_txt(10) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*7.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'Nxy'});
    % I
    S.ep_txt(11) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [tx, pdy+py-dd_dy*9.25, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'I'});
    % Nx
    S.dim_txt(1) = uicontrol('style','text',...
             'units','pixels',...
             'position', [tx*1.48, pdy+py-dd_dy, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'Nx'});
    % xmin
    S.dim_txt(2) = uicontrol('style','text',...
             'units','pixels',...
             'position', [tx*1.58, pdy+py-dd_dy, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'xmin'});
    % xmax
    S.dim_txt(3) = uicontrol('style','text',...
             'units','pixels',...
             'position', [tx*1.68, pdy+py-dd_dy, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'xmax'});
    % Ny
    S.dim_txt(4) = uicontrol('style','text',...
             'units','pixels',...
             'position', [tx*1.48, pdy+py-dd_dy*2.75, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'Ny'});
    % ymin
    S.dim_txt(5) = uicontrol('style','text',...
             'units','pixels',...
             'position', [tx*1.58, pdy+py-dd_dy*2.75, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'ymin'});
    % ymax
    S.dim_txt(6) = uicontrol('style','text',...
             'units','pixels',...
             'position', [tx*1.68, pdy+py-dd_dy*2.75, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'ymax'});         
    % Nz
    S.dim_txt(7) = uicontrol('style','text',...
             'units','pixels',...
             'position', [tx*1.48, pdy+py-dd_dy*4.35, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'Nz'});
    % zmin
    S.dim_txt(8) = uicontrol('style','text',...
             'units','pixels',...
             'position', [tx*1.58, pdy+py-dd_dy*4.35, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'zmin'});
    % zmax
    S.dim_txt(9) = uicontrol('style','text',...
             'units','pixels',...
             'position', [tx*1.68, pdy+py-dd_dy*4.35, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'zmax'});
   %% text edit
   % ELLIPTICAL
   edx = px+pdx+dd_dx; 
    % h
    S.ep_in(1) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'0.3'});          
    % ra
    S.ep_in(2) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*2, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'0.3'});
    % ri
    S.ep_in(3) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*3, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'0.3'});          
    % wT
    S.ep_in(4) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*4, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'0.1'});
    % N
    S.ep_in(5) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*5, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'2'});
    % O
    S.ep_in(6) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*7, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'1'});          
    % phi
    S.ep_in(7) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*8, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'2'});   
    % W
    S.ep_in(8) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*2, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'0.3'});
    % L
    S.ep_in(9) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*3, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'0.3'});   
    % Nxy
    S.ep_in(10) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*6, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'2'});
    % I
    S.ep_in(11) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [edx, pdy+py-dd_dy*9, dd_dx, dd_dy],...
                 'visible','on',...
                 'string',{'1'}); 
             
    dd_dx = 40; dd_dy = 25;
    % Nx
    S.dim_ep(1) = uicontrol('style','edit',...
             'units','pixels',...
             'position', [tx*1.5, pdy+py-dd_dy*1.5, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'50'});
    % xmin
    S.dim_ep(2) = uicontrol('style','edit',...
             'units','pixels',...
             'position', [tx*1.5+dd_dx, pdy+py-dd_dy*1.5, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'-0.74'});
    % xmax
    S.dim_ep(3) = uicontrol('style','edit',...
             'units','pixels',...
             'position', [tx*1.5+dd_dx*2, pdy+py-dd_dy*1.5, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'0.74'});      
    % Ny
    S.dim_ep(4) = uicontrol('style','edit',...
             'units','pixels',...
             'position', [tx*1.5, pdy+py-dd_dy*3.25, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'50'});
    % ymin
    S.dim_ep(5) = uicontrol('style','edit',...
             'units','pixels',...
             'position', [tx*1.5+dd_dx, pdy+py-dd_dy*3.25, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'-0.74'});
    % ymax
    S.dim_ep(6) = uicontrol('style','edit',...
             'units','pixels',...
             'position', [tx*1.5+dd_dx*2, pdy+py-dd_dy*3.25, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'0.74'});         
    % Nz
    S.dim_ep(7) = uicontrol('style','edit',...
             'units','pixels',...
             'position', [tx*1.5, pdy+py-dd_dy*4.95, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'50'});
    % zmin
    S.dim_ep(8) = uicontrol('style','edit',...
             'units','pixels',...
             'position', [tx*1.5+dd_dx, pdy+py-dd_dy*4.95, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'-0.74'});
    % zmax
    S.dim_ep(9) = uicontrol('style','edit',...
             'units','pixels',...
             'position', [tx*1.5+dd_dx*2, pdy+py-dd_dy*4.95, dd_dx, dd_dy],...
             'visible','on',...
             'string',{'0.74'});
% Callbacks: Set remaining properties.
    set(S.tg(:),{'callback'},{{@tg_call,S}});
end

% Callback for togglebuttons
    function [] = tg_call(varargin)
    ddList = {'m','cm','mm','in'};
    hList  = {'mil','m','cm','mm','in'};
    wtList = {'AWG','m','cm','mm','in'};
    dList  = {'deg','rad'}; 
    aList  = {'A','mA','uA','nA'};
    sList  = {'F','S'};
    AntDim.v = 'r';
    [h,S] = varargin{[1,3]};  % Get calling handle ans structure.
    getappdata(S.fh);
    
    % ZZ = get(S.ax,'children');  % The line object.
        switch h
            case S.tg(1)    %RECTANGULAR
                set([S.ax,S.dd],{'visible'},{'on'});
                set([S.ep_in(2),S.ep_in(3),S.ep_txt(2),S.ep_txt(3),S.dd],{'visible'},{'off'});
                set([S.ep_in(8),S.ep_in(9),S.ep_txt(8),S.ep_txt(9),S.dd],{'visible'},{'on'});
                AntDim.v = 'r';
            case S.tg(2)    % ELLIPTICAL
                set([S.ax],{'visible'},{'off'});
                set([S.ep_in(2),S.ep_in(3),S.ep_txt(2),S.ep_txt(3),S.dd],{'visible'},{'on'});
                set([S.ep_in(8),S.ep_in(9),S.ep_txt(8),S.ep_txt(9)],{'visible'},{'off'});
                AntDim.v = 'e';
            case S.tg(3) % IMPORT
                AntDim.v = 'k';
            case S.tg(4) % RUN
                % Update Units
                Units.h     = hList{S.dd(1).Value};
                Units.W     = ddList{S.dd(2).Value};
                Units.L     = ddList{S.dd(3).Value};
                Units.wT    = wtList{S.dd(4).Value};
                Units.phi   = dList{S.dd(5).Value};
                Units.dimx  = ddList{S.dim_dd(1).Value};
                Units.dimy  = ddList{S.dim_dd(2).Value};
                Units.dimz  = ddList{S.dim_dd(3).Value};
                Units.dimI  = aList{S.dim_dd(4).Value};
                Units.dimBF = sList{S.dim_dd(5).Value};
                % Update Antenna Dims
                AntDim.h   = str2double(char(S.ep_in(1).String));
                AntDim.ra  = str2double(char(S.ep_in(2).String));
                AntDim.ri  = str2double(char(S.ep_in(3).String));
                AntDim.wT  = str2double(char(S.ep_in(4).String));
                AntDim.N   = str2double(char(S.ep_in(5).String));
                AntDim.O   = str2double(char(S.ep_in(6).String));
                AntDim.phi = str2double(char(S.ep_in(7).String));
                AntDim.W   = str2double(char(S.ep_in(8).String));
                AntDim.L   = str2double(char(S.ep_in(9).String));
                AntDim.Nxy = str2double(char(S.ep_in(10).String));
                AntDim.I   = str2double(char(S.ep_in(11).String));
                % Update B-Fields Dims
                Bdim.Nx   = str2double(char(S.dim_ep(1).String));
                Bdim.xmin = str2double(char(S.dim_ep(2).String));   
                Bdim.xmax = str2double(char(S.dim_ep(3).String));  
                Bdim.Ny   = str2double(char(S.dim_ep(4).String)); 
                Bdim.ymin = str2double(char(S.dim_ep(5).String));  
                Bdim.ymax = str2double(char(S.dim_ep(6).String)); 
                Bdim.Nz   = str2double(char(S.dim_ep(7).String)); 
                Bdim.zmin = str2double(char(S.dim_ep(8).String)); 
                Bdim.zmax = str2double(char(S.dim_ep(9).String));
                Bdim.v    = sList{S.dim_dd(5).Value};
                % runs main code
                [A,B] =  main_UI(Units,AntDim,Bdim);
                % save A and B data into figure properties 'Userdata'
                set(S.fh,'UserData',struct('wireAnt',A,'BFields',B))
                nn=25; 
                HH = quiver3(S.bX(nn,:,:),S.bZ(nn,:,:),S.bY(nn,:,:),...
                    S.BX(nn,:,:),S.BZ(nn,:,:),S.BY(nn,:,:));
              
            case S.tg(5) % EXPORT
                % location of bfields
                newX = reshape(S.fh.UserData.BFields.X,...
                    numel(S.fh.UserData.BFields.BX),1);
                newY = reshape(S.fh.UserData.BFields.Y,...
                    numel(S.fh.UserData.BFields.Y),1);
                newZ = reshape(S.fh.UserData.BFields.Z,...
                    numel(S.fh.UserData.BFields.Z),1);
                % bfields
                newBX = reshape(S.fh.UserData.BFields.BX,...
                    numel(S.fh.UserData.BFields.BX),1);
                newBY = reshape(S.fh.UserData.BFields.BY,...
                    numel(S.fh.UserData.BFields.BY),1);
                newBZ = reshape(S.fh.UserData.BFields.BZ,...
                    numel(S.fh.UserData.BFields.BZ),1);
                dataM = [newX,newY,newZ,newBX,newBY,newBZ];
                T.Properties.VariableNames(1,1:3) = {'x','y','z',...
                    'BX','BY','BZ'};
                writetable(T,'antenna_wire_coordinates.csv');
                
                % antenna spatial coordinates [xyz]
                dataM = [S.fh.UserData.wireAnt.X,...
                    S.fh.UserData.wireAnt.Y,S.fh.UserData.wireAnt.Z];
                T = array2table(dataM);
                T.Properties.VariableNames(1,1:3) = {'x','y','z'};
                writetable(T,'antenna_wire_coordinates.csv')
               
            %case S.tg(6) % ABOUT
            %}
            otherwise       % IMPORT
                set([S.ax],{'visible'},{'off'});
        end 
    end