% Create a dipoleHelix antenna
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 25-Feb-2020 11:34:25

%% Antenna Properties 
% Design antenna at frequency 125000Hz
antennaObject = design(dipoleHelix,125000);
% Properties changed 
antennaObject.Width = 0.0002546;
antennaObject.Radius = 0.02;

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 125000;
% Define frequency range 
freqRange = (112.5:1.25:137.5) * 1e3;
% show for dipoleHelix
figure;
show(antennaObject) 
% current for dipoleHelix
figure;
current(antennaObject, plotFrequency) 
% pattern for dipoleHelix
figure;
pattern(antennaObject, plotFrequency) 
%%
hx = dipoleHelix('Width',0.02,'Radius',00002546);
figure;
EHfields(antennaObject,125e3)
%{
errors: 
Error using dipoleHelix/set.Width
Expected Width of helix to be a scalar with value >
10.184.

Error in dipoleHelix/createGeometry (line 182)
            validateattributes(W,{'numeric'},
            ...

Error in dipoleHelix/meshGenerator (line 257)
            createGeometry(obj);

Error in em.MeshGeometry/updateMesh

Error in em.MeshGeometry/getMesh

Error in em.EmStructures/analyze

Error in em.FieldAnalysisWithFeed/EHfields (line
164)
analyze(obj,parserObj.Results.frequency,
parserObj.Results.ElementNumber,
%}