
function [] = GUI_CHANGE_TEST()
    SCR = get(0,'Screensize');
    % creates overall figure 
    S.fh = figure('numbertitle','off',...
                  'menubar','none',...
                  'units','pixels',...
                  'position',[SCR(3)/2-200 ,SCR(4)/2-200 , 400, 400],...
                  'name','GUI_35',...
                  'resize','off');
    % creates empty plot
    S.ax = axes('units','pixels','position',[50 100 300 230]);
    % Toggles/Tabs
    S.tg(1) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[5 355 60 40],...
                        'string','PLOT',...
                        'val',1);
    S.tg(2) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[65 355 60 40],...
                        'string','FIT',...
                        'value',0,...
                        'enable','off');
    S.tg(3) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[125 355 60 40],...
                        'string','ABOUT',...
                        'value',0,...
                        'enable','on');
    % Callbacks
    set(S.tg(:),{'callback'},{{@tg_call,S}});
    
    function [] tg_call(varargin)
            [h,S] = varargin{[1,3]};
            L = get(S.ax,'children');
        switch h
            case S.tg(1) % Rect 
                set(S.tg([2,3]),{'val'},{0}) 
                set(S.tg([3,3]),{'val'},{0}) 
                set([S.ax],{'visible'},{'on'})
            case S.tg(2) % Circle
                set(S.tg([1,3]),{'val'},{0}) 
                set(S.tg([3,3]),{'val'},{0}) 
                set([S.ax],{'visible'},{'off'})
            otherwise % S.tg(3) % Other
                set(S.tg([1,3]),{'val'},{0}) 
                set(S.tg([2,3]),{'val'},{0}) 
        end
