
function [] = GUI_TEST()
% intialize variables

SCR = get(0,'Screensize'); % get screensize
% main fig
S.fh = figure('numbertitle','off',...
              'menubar','none',...
              'units','pixels',...
              'position',[SCR(3)/4-200 ,SCR(4)/4-200 , 825, 400],...
              'name','GUI_35',...
              'resize','off');
%% plot
S.ax  = axes('units','pixels','position',[50 100 300 230]);        
S.ax2 = axes('units','pixels','position',[500 100 300 230]); 
% run button        
S.pb1 = uicontrol('style','pushbutton',...
                  'units','pixels',...
                  'position',[50 20 300 40],...
                  'string','Compute B-Fields',...
                  'fontsize',12);
%% drop down list
S.dd = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[365 355 90 30],...
                 'string',{'Elliptical','Circular','Rectangular','Custom'});
                
%% Toggles will act as tabs
S.tg(1) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[5 355 60 40],...
                    'string','PLOT',...
                    'val',1);
S.tg(2) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[65 355 60 40],...
                    'string','RUN',...
                    'value',0,...
                    'enable','off');                
S.tg(3) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[125 355 60 40],...
                    'string','EXPORT',...
                    'value',0,...
                    'enable','off');
S.tg(4) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[185 355 60 40],...
                    'string','ABOUT',...
                    'value',0,...
                    'enable','on');
%% text page
S.tx = uicontrol('style','edit',...
                 'units','pixels',...
                 'position',[20 20 360 300],...
                 'visible','off',...
                 'string',{' ','This is a GUI with', 'fake tabs.',...
                 'Hope you enjoy'},...
                 'fontsize',20,'fontweight','bold');                
%% EDIT/Input boxes 
S.in = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [365, 100, 100, 30],...
                 'visible','on',...
                 'string',{'Option 1'});
%                  'fontsize',20,'fontweight','bold');
%% TEXT
S.txt = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [365, 50, 100, 30],...
                 'visible','on',...
                 'string',{'Option 1'});


%% Set remaining properties.
set(S.pb1,'callback',{@pb_call,S});          % Set push button callbacks.
set(S.tg(:),{'callback'},{{@tg_call,S}});    % Set toggle callbacks.
% set(S.in,'callback',{@txt_call,S});          % Set text callback
% set(S.ed(:),'visible','off','fontsize',12,'fontweight','bold',...
%    'backgroundcolor',[1 1 1])
end

%% callback for pushbutton
function [] = pb_call(varargin)
x = -10:.1:10; % For the plot.
plot(x,polyval(-5 + ceil(rand(1,5)*7),x));  % Plot some random quartic
set(varargin{3}.tg(2),'enable','on');  % Turn on 'Fit' tab.
end


%% Callback for toggle buttons
function [r] = tg_call(varargin)
global r
[h,S] = varargin{[1,3]};    % Get calling handle ans structure.
if get(h,'val')==0          % Here the Toggle is already pressed.
    set(h,'val',1)          % To keep the Tab-like functioning.
end
L = get(S.ax,'children');   % The line object

    switch h
        case S.tg(1) % PLOT
            set(S.tg([2,3]),'val',0);   
            set([S.ax,S.pb1,L],{'visible'},{'on'});
            % set([S.ed(:);S.tx],{'visible'},{'off'})
            set(S.tx,{'visible'},{'off'});
            
            r = get(S.in, 'String')
            
        case S.tg(2) % RUN
            set(S.tg([1,3]),{'val'},{0})
            % set(S.ed(:),{'visible'},{'on'})
            set([S.ax,S.pb1,L,S.tx],{'visible'},{'off'})
            STR = 'The x^0 coefficient is:  ';
            p = round(polyfit(get(L,'xdata'),get(L,'ydata'),4));
            for ii = 0:4
                STR(7) = num2str(ii);
                set(S.ed(5-ii),'str',[STR,num2str(p(5-ii))])
            end            
            
        otherwise
            set(S.tg([1,2]),{'val'},{0})
            set(S.tx,'visible','on')
            % set([S.ax;S.pb1;L;S.ed(:)],{'visible'},{'off'}) 
            set([S.ax;S.pb1;L],{'visible'},{'off'})
    end
end

%% Update Data
function getAndUpdate(handles)
    gotData = gotData(handles);
end

function updateData()

end
%{
function [] = dd_call(varargin)
end
function [] = pb_run(varargin)
end
%}