function [] = GUI_CHANGE_PAGE_TEST()
    SCR = get(0,'Screensize');
    % creates figure
    S.fh = figure('numbertitle','off',...
                  'menubar','none',...
                  'units','pixels',...
                  'position',[SCR(3)/4-200 ,SCR(4)/4-200 , 825, 400],...
                  'name','Wire Antenna Design Tool',...
                  'resize','off');
    % creates empty plot
    S.ax = axes('units','pixels','position',[50 100 300 230]);
   
    % Toggles will act as the tabs.              
    S.tg(1) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[5 355 60 40],...
                        'string','PLOT',...
                        'val',1);
    S.tg(2) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[65 355 60 40],...
                        'string','FIT',...
                        'value',1,...
                        'enable','on');
    S.tg(3) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[125 355 60 40],...
                        'string','ABOUT',...
                        'value',1,...
                        'enable','on');
    % drop down list
    ddx = 425;
    ddy = 100;
    dd_dimx = 50;
    dd_dimy = 25;
    S.dd(1) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[ddx ddy dd_dimx dd_dimy],...
                 'string',{'[m]','[cm]','[mm]','[in]'});  
    S.dd(2) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[ddx ddy+50 dd_dimx dd_dimy],...
                 'string',{'[m]','[cm]','[mm]','[in]'});  
    S.dd(3) = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[ddx ddy+100 dd_dimx dd_dimy],...
                 'string',{'[m]','[cm]','[mm]','[in]'});  
   
    % text and text edit boxes
    txt_offx = -50;
    txt_offy = -20;
    S.ep_txt(1) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [ddx+txt_offx, 170, dd_dimx, dd_dimy],...
                 'visible','on',...
                 'string',{'Ra'});
    S.ep_in(1) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [ddx+txt_offx, 150, dd_dimx, dd_dimy],...
                 'visible','on',...
                 'string',{'30'});            
    S.ep_txt(2) = uicontrol('style','text',...
                 'units','pixels',...
                 'position', [ddx+txt_offx, 170+30, dd_dimx, dd_dimy],...
                 'visible','on',...
                 'string',{'Ri'});
    S.ep_in(2) = uicontrol('style','edit',...
                 'units','pixels',...
                 'position', [ddx+txt_offx, 150+60, dd_dimx, dd_dimy],...
                 'visible','on',...
                 'string',{'30'});            
    % Callbacks: Set remaining properties.
    % toggles
    set(S.tg(:),{'callback'},{{@tg_call,S}})

    % Callback for togglebuttons.
    function [] = tg_call(varargin)
    [h,S] = varargin{[1,3]}  % Get calling handle ans structure.
    L = get(S.ax,'children');  % The line object.

    switch h
        case S.tg(1) %PLOT
            %sset(S.tg([2,3]),{'val'},{0})
            %set(S.tg([3,3]),{'val'},{0})
            set([S.ax,S.dd],{'visible'},{'on'})
        case S.tg(2) % FIT
            %set(S.tg([1,3]),{'val'},{0})
            %set(S.tg([3,3]),{'val'},{0})
            set([S.ax],{'visible'},{'off'})
        otherwise % ABOUT
            %set(S.tg([1,3]),{'val'},{0})
            %set(S.tg([2,3]),{'val'},{0})
            set([S.ax],{'visible'},{'ff'})
    end