
function [] = GUI_CHANGE_PAGE()
    SCR = get(0,'Screensize');
    % creates figure
    S.fh = figure('numbertitle','off',...
                  'menubar','none',...
                  'units','pixels',...
                  'position',[SCR(3)/2-200 ,SCR(4)/2-200 , 400, 400],...
                  'name','GUI_35',...
                  'resize','off');
    % creates empty plot
    S.ax = axes('units','pixels','position',[50 100 300 230]);
    
    % Toggles will act as the tabs.              
    S.tg(1) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[5 355 60 40],...
                        'string','PLOT',...
                        'val',1);
    S.tg(2) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[65 355 60 40],...
                        'string','FIT',...
                        'value',1,...
                        'enable','on');
    S.tg(3) = uicontrol('style','toggle',...
                        'units','pixels',...
                        'position',[125 355 60 40],...
                        'string','ABOUT',...
                        'value',1,...
                        'enable','on');
    S.dd = uicontrol('style','popupmenu',...
                 'units','pixels',...
                 'position',[365 355 90 30],...
                 'string',{'Elliptical','Circular','Rectangular','Custom'});            
    % Callbacks: Set remaining properties.
    % toggles
    set(S.tg(:),{'callback'},{{@tg_call,S}})

    % Callback for togglebuttons.
    function [] = tg_call(varargin)
    [h,S] = varargin{[1,3]}  % Get calling handle ans structure.
    L = get(S.ax,'children');  % The line object.

    switch h
        case S.tg(1) %PLOT
            %sset(S.tg([2,3]),{'val'},{0}) 
            %set(S.tg([3,3]),{'val'},{0}) 
            set([S.ax,S.dd],{'visible'},{'on'})
        case S.tg(2) % FIT
            %set(S.tg([1,3]),{'val'},{0}) 
            %set(S.tg([3,3]),{'val'},{0}) 
            set([S.ax],{'visible'},{'off'})
        otherwise % ABOUT
            %set(S.tg([1,3]),{'val'},{0}) 
            %set(S.tg([2,3]),{'val'},{0}) 
            set([S.ax],{'visible'},{'ff'})
    end

